version: '3.8'

services:

  base:
    build:
      context: ./docker
      dockerfile: base.dockerfile
    volumes:
      - ./docker/volumes/certbot:/var/certbot/
      - ./docker/volumes/letsencrypt/:/etc/letsencrypt/

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    restart: "always"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/config/nginx/sites:/var/www
      - ./docker/volumes/certbot:/var/certbot/
      - ./docker/volumes/letsencrypt/:/etc/nginx/ssl/

  mailserver:
    build:
      context: ./docker
      dockerfile: mailserver.dockerfile
    hostname: mail
    domainname: <domain>
    env_file: ./docker/config/mailserver/mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker/volumes/mailserver/mail-data/:/var/mail/
      - ./docker/volumes/mailserver/mail-state/:/var/mail-state/
      - ./docker/volumes/mailserver/mail-logs/:/var/log/mail/
      - ./docker/volumes/mailserver/config/:/tmp/docker-mailserver/
      - ./docker/volumes/letsencrypt/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    
  # pgsql:
  #   build:
  #     context: ./docker
  #     dockerfile: pgsql.dockerfile
  #   restart: "always"
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     PGPASSWORD: 'secret'
  #     POSTGRES_DB: 'base'
  #     POSTGRES_USER: 'user'
  #     POSTGRES_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/pgsql/data:/var/lib/postgresql/data'

  # mysql:
  #   build:
  #     context: ./docker
  #     dockerfile: mysql.dockerfile
  #   restart: "always"
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_DATABASE: 'base'
  #     MYSQL_ROOT_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/mysql/data:/var/lib/mysql'

  # mariadb:
  #   build:
  #     context: ./docker
  #     dockerfile: mariadb.dockerfile
  #   restart: "always"
  #   ports:
  #     - '33066:33066'
  #   environment:
  #     MARIADB_DATABASE: 'base'
  #     MARIADB_ROOT_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/mariadb/data:/var/lib/mysql'

  # mongo:
  #   build:
  #     context: ./docker
  #     dockerfile: mongo.dockerfile
  #   restart: "always"
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: 'root'
  #     MONGO_INITDB_ROOT_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/mongo/data:/data/db'

  # redis:
  #   build:
  #     context: ./docker
  #     dockerfile: mongo.dockerfile
  #   restart: "always"
  #   ports:
  #     - 6379:6379
  #   volumes: 
  #     - ./docker/volumes/redis/data:/data
