version: '3.8'

services:

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    restart: "always"
    ports:
      - 8080:80
    volumes:
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/config/nginx/sites/base:/var/www/base

  # mailserver:
  #   build:
  #     context: ./docker
  #     dockerfile: mailhog.dockerfile
  #   restart: "always"
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"

  # ruby:
  #   build:
  #     context: ./docker
  #     dockerfile: ruby.dockerfile
  #   restart: "always"
  #   expose:
  #     - 9000

  # python:
  #   build:
  #     context: ./docker
  #     dockerfile: python.dockerfile
  #   restart: "always"
  #   expose:
  #     - 9000

  # node:
  #   build:
  #     context: ./docker
  #     dockerfile: node.dockerfile
  #   restart: "always"
  #   expose:
  #     - 9000

  # php:
  #   build:
  #     context: ./docker
  #     dockerfile: php.dockerfile
  #   restart: "always"
  #   expose:
  #     - 9000
  #   volumes:
  #     - ./docker/config/nginx/sites/php:/var/www/php
  #     - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # wordpress:
  #   build:
  #     context: ./docker
  #     dockerfile: wordpress.dockerfile
  #   restart: "always"
  #   expose:
  #     - 9000
  #   environment:
  #     WORDPRESS_DB_HOST: mysql
  #     WORDPRESS_DB_USER: user
  #     WORDPRESS_DB_PASSWORD: secret
  #     WORDPRESS_DB_NAME: base
  #   volumes:
  #     - ./docker/volumes/wordpress/data:/var/www/html
    
  # pgsql:
  #   build:
  #     context: ./docker
  #     dockerfile: pgsql.dockerfile
  #   restart: "always"
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     PGPASSWORD: 'secret'
  #     POSTGRES_DB: 'base'
  #     POSTGRES_USER: 'user'
  #     POSTGRES_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/pgsql/data:/var/lib/postgresql/data'

  # mysql:
  #   build:
  #     context: ./docker
  #     dockerfile: mysql.dockerfile
  #   restart: "always"
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_DATABASE: 'base'
  #     MYSQL_ROOT_PASSWORD: 'secret'
  #     MYSQL_USER: 'user'
  #     MYSQL_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/mysql/data:/var/lib/mysql'

  # mariadb:
  #   build:
  #     context: ./docker
  #     dockerfile: mariadb.dockerfile
  #   restart: "always"
  #   ports:
  #     - '33066:33066'
  #   environment:
  #     MARIADB_DATABASE: 'base'
  #     MARIADB_ROOT_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/mariadb/data:/var/lib/mysql'

  # mongo:
  #   build:
  #     context: ./docker
  #     dockerfile: mongo.dockerfile
  #   restart: "always"
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: 'root'
  #     MONGO_INITDB_ROOT_PASSWORD: 'secret'
  #   volumes:
  #     - './docker/volumes/mongo/data:/data/db'

  # redis:
  #   build:
  #     context: ./docker
  #     dockerfile: mongo.dockerfile
  #   restart: "always"
  #   ports:
  #     - 6379:6379
  #   volumes: 
  #     - ./docker/volumes/redis/data:/data
